In [1]:
import pandas as pd
import numpy as np

In [3]:
df=pd.read_csv('/home/manjula/python/cleaning/Datasets/Book.csv')
print( df.shape)
print(df.head())

(8287, 15)
   Identifier             Edition Statement      Place of Publication  \
0         206                           NaN                    London
1         216                           NaN  London; Virtue & Yorston
2         218                           NaN                    London
3         472                           NaN                    London
4         480  A new edition, revised, etc.                    London

  Date of Publication              Publisher  \
0         1879 [1878]       S. Tinsley & Co.
1                1868           Virtue & Co.
2                1869  Bradbury, Evans & Co.
3                1851          James Darling
4                1857   Wertheim & Macintosh

                                               Title     Author  \
0                  Walter Forbes. [A novel.] By A. A      A. A.
1  All for Greed. [A novel. The dedication signed...  A., A. A.
2  Love the Avenger. By the author of “All for Gr...  A., A. A.
3  Welsh Sketches, chiefly ecclesiastical, to the...  A., E. S.
4  [The World in which I live, and my place in it...  A., E. S.

                                   Contributors  Corporate Author  \
0                               FORBES, Walter.               NaN
1  BLAZE DE BURY, Marie Pauline Rose - Baroness               NaN
2  BLAZE DE BURY, Marie Pauline Rose - Baroness               NaN
3                   Appleyard, Ernest Silvanus.               NaN
4                           BROOME, John Henry.               NaN

   Corporate Contributors Former owner  Engraver Issuance type  \
0                     NaN          NaN       NaN   monographic
1                     NaN          NaN       NaN   monographic
2                     NaN          NaN       NaN   monographic
3                     NaN          NaN       NaN   monographic
4                     NaN          NaN       NaN   monographic

                                          Flickr URL  \
0  http://www.flickr.com/photos/britishlibrary/ta...
1  http://www.flickr.com/photos/britishlibrary/ta...
2  http://www.flickr.com/photos/britishlibrary/ta...
3  http://www.flickr.com/photos/britishlibrary/ta...
4  http://www.flickr.com/photos/britishlibrary/ta...

                            Shelfmarks
0    British Library HMNTS 12641.b.30.
1    British Library HMNTS 12626.cc.2.
2    British Library HMNTS 12625.dd.1.
3  British Library HMNTS 10369.bbb.15.
4     British Library HMNTS 9007.d.28.

In [4]:
to_drop= ['Edition Statement',
           'Corporate Author',
            'Corporate Contributors',
            'Former owner',
            'Engraver',
            'Contributors',
            'Issuance type',
            'Shelfmarks']

In [5]:
df.drop(to_drop,inplace=True,axis=1)

In [7]:
print (df.shape)

print (df.head())

(8287, 7)
   Identifier      Place of Publication Date of Publication  \
0         206                    London         1879 [1878]
1         216  London; Virtue & Yorston                1868
2         218                    London                1869
3         472                    London                1851
4         480                    London                1857

               Publisher                                              Title  \
0       S. Tinsley & Co.                  Walter Forbes. [A novel.] By A. A
1           Virtue & Co.  All for Greed. [A novel. The dedication signed...
2  Bradbury, Evans & Co.  Love the Avenger. By the author of “All for Gr...
3          James Darling  Welsh Sketches, chiefly ecclesiastical, to the...
4   Wertheim & Macintosh  [The World in which I live, and my place in it...

      Author                                         Flickr URL
0      A. A.  http://www.flickr.com/photos/britishlibrary/ta...
1  A., A. A.  http://www.flickr.com/photos/britishlibrary/ta...
2  A., A. A.  http://www.flickr.com/photos/britishlibrary/ta...
3  A., E. S.  http://www.flickr.com/photos/britishlibrary/ta...
4  A., E. S.  http://www.flickr.com/photos/britishlibrary/ta...

In [8]:
df.set_index('Identifier')

,Place of Publication,Date of Publication,Publisher,Title,Author,Flickr URL
Identifier,,,,,,
206,London,1879 [1878],S. Tinsley & Co.,Walter Forbes. [A novel.] By A. A,A. A.,http://www.flickr.com/photos/britishlibrary/ta...
216,London; Virtue & Yorston,1868,Virtue & Co.,All for Greed. [A novel. The dedication signed...,"A., A. A.",http://www.flickr.com/photos/britishlibrary/ta...
218,London,1869,"Bradbury, Evans & Co.",Love the Avenger. By the author of “All for Gr...,"A., A. A.",http://www.flickr.com/photos/britishlibrary/ta...
472,London,1851,James Darling,"Welsh Sketches, chiefly ecclesiastical, to the...","A., E. S.",http://www.flickr.com/photos/britishlibrary/ta...
480,London,1857,Wertheim & Macintosh,"[The World in which I live, and my place in it...","A., E. S.",http://www.flickr.com/photos/britishlibrary/ta...
481,London,1875,William Macintosh,"[The World in which I live, and my place in it...","A., E. S.",http://www.flickr.com/photos/britishlibrary/ta...
519,London,1872,The Author,Lagonells. By the author of Darmayne (F. E. A....,"A., F. E.",http://www.flickr.com/photos/britishlibrary/ta...
667,"pp. 40. G. Bryan & Co: Oxford, 1898",NaN,NaN,"The Coming of Spring, and other poems. By J. A...","A., J.|A., J.",http://www.flickr.com/photos/britishlibrary/ta...
874,London],1676,NaN,"A Warning to the inhabitants of England, and L...",Remaʿ.,http://www.flickr.com/photos/britishlibrary/ta...
1143,London,1679,NaN,A Satyr against Vertue. (A poem: supposed to b...,"A., T.",http://www.flickr.com/photos/britishlibrary/ta...
1280,Coventry,1802,Printed by J. Turner,"An Account of the many and great Loans, Benefa...",NaN,http://www.flickr.com/photos/britishlibrary/ta...
1808,Christiania,1859,NaN,Erindringer som Bidrag til Norges Historie fra...,"AALL, Jacob.",http://www.flickr.com/photos/britishlibrary/ta...
1905,Firenze,1888,NaN,Gli Studi storici in terra d'Otranto ... Framm...,"AAR, Ermanno - pseud. [i.e. Luigi Giuseppe Oro...",http://www.flickr.com/photos/britishlibrary/ta...
1929,Amsterdam,"1839, 38-54",NaN,De Aardbol. Magazijn van hedendaagsche land- e...,NaN,http://www.flickr.com/photos/britishlibrary/ta...
2836,Savona,1897,NaN,Cronache Savonesi dal 1500 al 1570 ... Accresc...,"ABATE, Giovanni Agostino.",http://www.flickr.com/photos/britishlibrary/ta...
2854,London,1865,E. Moxon & Co.,"See-Saw; a novel ... Edited [or rather, writte...","ABATI, Francesco.",http://www.flickr.com/photos/britishlibrary/ta...
2956,Paris,1860-63,NaN,"Géodésie d'une partie de la Haute Éthiopie,...","ABBADIE, Antoine Thompson d'.",http://www.flickr.com/photos/britishlibrary/ta...
2957,Paris,1873,NaN,[With eleven maps.],"ABBADIE, Antoine Thompson d'.",http://www.flickr.com/photos/britishlibrary/ta...
3017,Puerto-Rico,1866,NaN,"[Historia geográfica, civil y politica de la ...","ABBAD Y LASIERRA, Agustín Íñigo - Bishop of...",http://www.flickr.com/photos/britishlibrary/ta...
3131,New York,1899,W. Abbatt,"The Crisis of the Revolution, being the story ...","ABBATT, William.",http://www.flickr.com/photos/britishlibrary/ta...
4598,Hull,1814,The Author,Peace: a lyric poem. [With prefatory address b...,"ABBOTT, Thomas Eastoe.",http://www.flickr.com/photos/britishlibrary/ta...
4884,London,1820,J. Hatchard & Son,"Abdallah; or, The Arabian Martyr: a Christian ...",NaN,http://www.flickr.com/photos/britishlibrary/ta...
4976,Oxonii,1800,"J. Cooke, etc.",[Abdollatiphi Historiæ Ægypti compendium. [Wit...,NaN,http://www.flickr.com/photos/britishlibrary/ta...
5382,London,"1847, 48 [1846-48]",Punch Office,The Comic History of England ... With ... colo...,"A'BECKETT, Gilbert Abbott.",http://www.flickr.com/photos/britishlibrary/ta...
5385,London,[1897?],"Bradbury, Agnew & Co.",[The comic history of England ... With twenty ...,"A'BECKETT, Gilbert Abbott.",http://www.flickr.com/photos/britishlibrary/ta...
5389,London,[1897?],"Bradbury, Agnew & Co.",[The Comic History of Rome ... Illustrated by ...,"A'BECKETT, Gilbert Abbott.",http://www.flickr.com/photos/britishlibrary/ta...
5432,Milano,1893,NaN,Signa: opera in tre atti [founded on the novel...,"A'BECKETT, Gilbert Arthur - and RUDALL (H. A.)",http://www.flickr.com/photos/britishlibrary/ta...
6036,London,1805,C. & R. Baldwin,"The Venetian Outlaw, a drama in three acts ......",NaN,http://www.flickr.com/photos/britishlibrary/ta...
6821,Aberdeen,1837,J. Davidson & Co.,Description of the Coast between Aberdeen and ...,NaN,http://www.flickr.com/photos/britishlibrary/ta...
7521,Wien,1896,NaN,Aus Kaukasischen Ländern. Reisebriefe von H. ...,"ABICH, Wilhelm Hermann.",http://www.flickr.com/photos/britishlibrary/ta...
...,...,...,...,...,...,...
4053464,"London: E. Nutt; E. Cooke, 1733",NaN,NaN,A friendly epistle [by Joseph Mitchell?] to th...,NaN,http://www.flickr.com/photos/britishlibrary/ta...
4063671,London,1896,Richard Bentley & Son,Honor Ormthwaite. By the author of “Lady Jean'...,"KEDDIE, Henrietta.",http://www.flickr.com/photos/britishlibrary/ta...
4072044,"London: D. Wilson & T. Durham, 1752",NaN,NaN,"The scale: or, Woman weighed with man. A poem ...","MONCREIFF, John.",http://www.flickr.com/photos/britishlibrary/ta...
4077038,"London: printed for Nicholas Vavasour, 1634",NaN,NaN,"The noble souldier. Or, A contract broken, jus...","ROWLEY, Samuel - Dramatist",http://www.flickr.com/photos/britishlibrary/ta...
4079258,Glasgow,1750,"printed for John Ross, bookseller in Edinburgh",[Yarico to Inkle.] The epistle of Yarico to In...,NaN,http://www.flickr.com/photos/britishlibrary/ta...
4079262,London,1879,NaN,The Canadian farmer. A missionary incident. [S...,"YATES, William Joseph H.",http://www.flickr.com/photos/britishlibrary/ta...
4112297,"London: Macmillan & Co., pp. xl, 400. 1895",NaN,NaN,Japhet in search of a Father ... With an intro...,"Marryat, Frederick",http://www.flickr.com/photos/britishlibrary/ta...
4112525,Pontoise,1889,NaN,Histoire populaire de Pontoise ... Précédée...,"DEPOIN, Joseph.",http://www.flickr.com/photos/britishlibrary/ta...
4112839,London,[1845.],Willoughby & Co.,The Vicar of Wakefield ... And a prefatory mem...,"Goldsmith, Oliver",http://www.flickr.com/photos/britishlibrary/ta...
4113012,Philadelphia,1876,S. W. Burley,1776 American Enterprise. 1876. Burley's Unite...,"KIDDER, Charles Holland.|Pope, Alexander",http://www.flickr.com/photos/britishlibrary/ta...
4113816,"pp. xxvi, 375. London: Jackson, Walford & Hodd...",NaN,NaN,The lacemakers: sketches of Irish characters w...,"MEREDITH, Susanna.|WIBERG, Carl Fredrik.",http://www.flickr.com/photos/britishlibrary/ta...
4114334,"pp. viii. 64. J. Debrett: London, 1789",NaN,NaN,"The Sword of Peace; or, a voyage of love; a co...",NaN,http://www.flickr.com/photos/britishlibrary/ta...
4114390,London,1708,NaN,"THe Unfortunate Dutchess of Malfy, or, The Unn...","WEBSTER, John - Dramatist|SCOTT, Michael - of ...",http://www.flickr.com/photos/britishlibrary/ta...
4114889,London,[1868],NaN,"The 5 Alls. A collection of stories, charades,...",NaN,http://www.flickr.com/photos/britishlibrary/ta...
4114986,London,1777,J. Wenman,[Barbarossa. A tragedy. As it is performed at ...,"BROWN, John - Vicar of Newcastle-upon-Tyne",http://www.flickr.com/photos/britishlibrary/ta...
4115138,"G. Eld: London, 1608",NaN,NaN,The Revenger's Tagaedie. As it hath beene sund...,NaN,http://www.flickr.com/photos/britishlibrary/ta...
4116063,London,1866,[John Dicks],"Edith Heron; or, the Earl and the countess. [B...","HERON, Edith.",http://www.flickr.com/photos/britishlibrary/ta...
4117526,Leipzig,1862,Charles Fr. Fleischer,Abridgment of the History of England ... Adapt...,"Goldsmith, Oliver",http://www.flickr.com/photos/britishlibrary/ta...
4117583,London,1894,T. Fisher Unwin,The Wish. A novel by Hermann Sudermann. Transl...,"SUDERMANN, Hermann.",http://www.flickr.com/photos/britishlibrary/ta...
4117749,New York,1868,John Wiley & Son,A System of Mineralogy. Descriptive Mineralogy...,"DANA, James Dwight.",http://www.flickr.com/photos/britishlibrary/ta...
4117751,New York,1882,John Wiley & Sons,Third Appendix to the fifth edition of Dana's ...,"DANA, James Dwight.",http://www.flickr.com/photos/britishlibrary/ta...
4117752,London,"1883, [1884]",Trübner & Co.,"A System of Mineralogy ... Fifth edition, rewr...","DANA, James Dwight.",http://www.flickr.com/photos/britishlibrary/ta...
4156359,New York,1898-1912,G. P. Putnam's Sons,History of the People of the Netherlands ... T...,"BLOK, Pieter Johan.",http://www.flickr.com/photos/britishlibrary/ta...
4157746,London,1811,F. C. and J. Rivington,"The New Chronicles of England and France, in t...","FABYAN, Robert.",http://www.flickr.com/photos/britishlibrary/ta...
4157862,Newcastle-upon-Tyne,1867,T. Fordyce,"Local Records; or, Historical Register of rema...","FORDYCE, T. - Printer, of Newcastle-upon-Tyne",http://www.flickr.com/photos/britishlibrary/ta...
4158088,London,1838,NaN,"The Parochial History of Cornwall, founded on,...","GIDDY, afterwards GILBERT, Davies.",http://www.flickr.com/photos/britishlibrary/ta...
4158128,Derby,"1831, 32",M. Mozley & Son,The History and Gazetteer of the County of Der...,"GLOVER, Stephen - of Derby",http://www.flickr.com/photos/britishlibrary/ta...
4159563,London,[1806]-22,T. Cadell and W. Davies,Magna Britannia; being a concise topographical...,"LYSONS, Daniel - M.A., F.R.S., and LYSONS (Sam...",http://www.flickr.com/photos/britishlibrary/ta...
4159587,Newcastle upon Tyne,1834,Mackenzie & Dent,"An historical, topographical and descriptive v...","Mackenzie, E. (Eneas)",http://www.flickr.com/photos/britishlibrary/ta...
4160339,London,1834-43,NaN,Collectanea Topographica et Genealogica. [Firs...,NaN,http://www.flickr.com/photos/britishlibrary/ta...

In [10]:
df.loc[206]

Identifier                                                          77554
Place of Publication                                               London
Date of Publication                                                  1848
Publisher                                                 Richard Bentley
Title                   Rambles in the romantic regions of the Hartz M...
Author                                   Andersen, H. C. (Hans Christian)
Flickr URL              http://www.flickr.com/photos/britishlibrary/ta...
Name: 206, dtype: object

In [11]:
df.loc[472]

Identifier                                                         188382
Place of Publication                                                Paris
Date of Publication                                                  1894
Publisher                                                             NaN
Title                     Balmaceda, su gobierno y la revolución de 1891
Author                                          BAÑADOS ESPINOSA, Julio.
Flickr URL              http://www.flickr.com/photos/britishlibrary/ta...
Name: 472, dtype: object

In [12]:
df.iloc[0]

Identifier                                                            206
Place of Publication                                               London
Date of Publication                                           1879 [1878]
Publisher                                                S. Tinsley & Co.
Title                                   Walter Forbes. [A novel.] By A. A
Author                                                              A. A.
Flickr URL              http://www.flickr.com/photos/britishlibrary/ta...
Name: 0, dtype: object

In [13]:
df.get_dtype_counts()

int64     1
object    6
dtype: int64

In [20]:
df.loc[206:, 'Date of Publication'].head(10)

206       1848
207       1891
208       1859
209     [1890]
210       1876
211       1899
212       1875
213       1895
214    [1885?]
215       1883
Name: Date of Publication, dtype: object

In [21]:
regex = r'^(\d{4})'

In [22]:
extr=df['Date of Publication'].str.extract(r'^(\d{4})',expand=False)

In [25]:
extr.head(10)

0    1879
1    1868
2    1869
3    1851
4    1857
5    1875
6    1872
7     NaN
8    1676
9    1679
Name: Date of Publication, dtype: object

In [26]:
df['Date of publication']=pd.to_numeric(extr)

In [27]:
df['Date of publication'].dtype

dtype('float64')

In [28]:
len(df)

8287

In [29]:
df['Date of publication'].isnull().sum

<bound method Series.sum of 0       False
1       False
2       False
3       False
4       False
5       False
6       False
7        True
8       False
9       False
10      False
11      False
12      False
13      False
14      False
15      False
16      False
17      False
18      False
19      False
20      False
21      False
22      False
23      False
24       True
25       True
26      False
27      False
28      False
29      False
        ...
8257     True
8258    False
8259     True
8260     True
8261    False
8262    False
8263     True
8264    False
8265     True
8266    False
8267     True
8268     True
8269    False
8270     True
8271    False
8272     True
8273    False
8274    False
8275    False
8276    False
8277    False
8278    False
8279    False
8280    False
8281    False
8282    False
8283    False
8284     True
8285    False
8286    False
Name: Date of publication, Length: 8287, dtype: bool>

In [31]:
df['Date of publication'].isnull().sum()/len(df)

0.11717147339205986

In [32]:
df.head()

,Identifier,Place of Publication,Date of Publication,Publisher,Title,Author,Flickr URL,Date of publication
0,206,London,1879 [1878],S. Tinsley & Co.,Walter Forbes. [A novel.] By A. A,A. A.,http://www.flickr.com/photos/britishlibrary/ta...,1879.0
1,216,London; Virtue & Yorston,1868,Virtue & Co.,All for Greed. [A novel. The dedication signed...,"A., A. A.",http://www.flickr.com/photos/britishlibrary/ta...,1868.0
2,218,London,1869,"Bradbury, Evans & Co.",Love the Avenger. By the author of “All for Gr...,"A., A. A.",http://www.flickr.com/photos/britishlibrary/ta...,1869.0
3,472,London,1851,James Darling,"Welsh Sketches, chiefly ecclesiastical, to the...","A., E. S.",http://www.flickr.com/photos/britishlibrary/ta...,1851.0
4,480,London,1857,Wertheim & Macintosh,"[The World in which I live, and my place in it...","A., E. S.",http://www.flickr.com/photos/britishlibrary/ta...,1857.0

In [33]:
df.loc[216
      ]

Identifier                                                          84631
Place of Publication                                             New York
Date of Publication                                                  1867
Publisher                                                 D. Van Nostrand
Title                   History of the Campaign of Mobile; including t...
Author                                     ANDREWS, Christopher Columbus.
Flickr URL              http://www.flickr.com/photos/britishlibrary/ta...
Date of publication                                                  1867
Name: 216, dtype: object

In [34]:
df.loc[472]

Identifier                                                         188382
Place of Publication                                                Paris
Date of Publication                                                  1894
Publisher                                                             NaN
Title                     Balmaceda, su gobierno y la revolución de 1891
Author                                          BAÑADOS ESPINOSA, Julio.
Flickr URL              http://www.flickr.com/photos/britishlibrary/ta...
Date of publication                                                  1894
Name: 472, dtype: object

In [ ]:
df.head(20)

In [37]:
df.iloc[8
       ]

Identifier                                                            874
Place of Publication                                              London]
Date of Publication                                                  1676
Publisher                                                             NaN
Title                   A Warning to the inhabitants of England, and L...
Author                                                             Remaʿ.
Flickr URL              http://www.flickr.com/photos/britishlibrary/ta...
Date of publication                                                  1676
Name: 8, dtype: object

In [39]:
df.iloc[9]

Identifier                                                           1143
Place of Publication                                               London
Date of Publication                                                  1679
Publisher                                                             NaN
Title                   A Satyr against Vertue. (A poem: supposed to b...
Author                                                             A., T.
Flickr URL              http://www.flickr.com/photos/britishlibrary/ta...
Date of publication                                                  1679
Name: 9, dtype: object

In [41]:
pub=df['Place of Publication']

In [42]:
london=pub.str.contains('London')

In [45]:
london[:10]

0     True
1     True
2     True
3     True
4     True
5     True
6     True
7    False
8     True
9     True
Name: Place of Publication, dtype: bool

In [46]:
oxford=pub.str.contains('Oxford')
oxford[:10]

0    False
1    False
2    False
3    False
4    False
5    False
6    False
7     True
8    False
9    False
Name: Place of Publication, dtype: bool

In [61]:
df['Place of Publication'] = np.where(london, 'London',
                                      np.where(oxford, 'Oxford',
                                               pub.str.replace('-', ' ')))                                     
#this problem arises with python 3.5 and belower version

TypeError: Type aliases cannot be used with isinstance().

In [62]:
df['Place of Publication'].head()

0                      London
1    London; Virtue & Yorston
2                      London
3                      London
4                      London
Name: Place of Publication, dtype: object